name: Build

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: print files
      run: dir 
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Restore Packages
      run: nuget restore hackathon.acumatica.theta.sln
      
    - name: Build Solution
      run: msbuild.exe hackathon.acumatica.theta.sln /nologo /nr:false /p:Configuration=Release /target:Rebuild
      
    - name: Move dll
      run: Copy-Item "hackathon.acumatica.theta/bin/Release/netstandard2.0/hackathon.acumatica.theta.*" -Destination "_projects\hackathon.acumatica.theta\Bin"
    
    - name: print dir
      run: dir _projects\hackathon.acumatica.theta\Bin
