name: Build

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: print files
      run: dir 
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Restore Packages
      run: nuget restore hackathon.acumatica.theta.sln
      
    - name: Build Solution
      run: msbuild.exe hackathon.acumatica.theta.sln /nologo /nr:false /p:Configuration=Release /target:Rebuild
      
    - name: print dir
      run: dir
    
    - name: Start SSH session
      uses: luchihoratiu/debug-via-ssh@main
      with:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK }}
        SSH_PASS: ${{ secrets.PASS }}
