name: Publish to prod

env:
  ProjectName : test

on:
  push:
    branches: ["main"]
    pull_request: ["main"]

  workflow_dispatch:

jobs:
  base64-encode-and-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login
        run: |
          # logs in
          loginJson='{"name":"githubaction","password":"Theta","company":"Company","branch":""}'
          curl -X POST https://hackathon.acumatica.com/Theta/entity/auth/login -H "Content-Type: application/JSON" -d $loginJson -i --cookie-jar ./cookies.txt