name: Build and Validate

env:
  ProjectName : test

on:
  push:
    branches: ["development"]
    pull_request: ["development"]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: print files
        run: dir

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore Packages
        run: nuget restore hackathon.acumatica.theta.sln

      - name: Build Solution
        run: msbuild.exe hackathon.acumatica.theta.sln /nologo /nr:false /p:Configuration=Release /target:Rebuild

      - name: Move dll
        run: Copy-Item "hackathon.acumatica.theta/bin/Release/netstandard2.0/hackathon.acumatica.theta.*" -Destination "_projects\hackathon.acumatica.theta\Bin"


      - name: Login
        shell: bash
        run: |
          ls | echo
          # logs in
          loginJson='{"name":"githubaction","password":"Theta","company":"Company","branch":""}'
          curl -X POST https://hackathon.acumatica.com/Theta/entity/auth/login -H "Content-Type: application/JSON" -d $loginJson -i --cookie-jar ./cookies.txt
      - name: Zips an Uploads
        shell: bash
        run: |
          #sends file
          zip build.zip _projects/hackathon.acumatica.theta/*
          base64=$(base64 build.zip)
          projectJson='{"projectLevel":1,"isReplaceIfExists":true,"projectName":"test","projectDescription":"Customization Project for Team Theta","projectContentBase64":"'"$base64"'"}'
          curl --location --request POST 'https://hackathon.acumatica.com/Theta/CustomizationApi/Import' --header 'Content-Type: application/json' -d "$projectJson" -i -b ./cookies.txt
      - name: Validate Project
        shell: bash
        run:
          ./.github/scripts/validate.sh
